# GENERATED by sapohub-deploy — UI preferences synced from the hub.
# lib.mkDefault: anything you set on services.sapohub.prefs directly wins.
{ lib, ... }:
{
  services.sapohub.prefs = lib.mapAttrs (_: lib.mkDefault) (builtins.fromJSON ''
{
  "dashboard_button.my_plate": "preview",
  "dashboard_order": "my_plate,reminders,projects,storage,magic_proxies,youtube_download",
  "statusline_order": "my_plate.due"
}
'');
}
