# Fallback boot mode — see disk-config.nix's header comment. The real
# boot-mode.nix is generated by scripts/remote-deploy.sh on every run
# (from --boot-mode) and is gitignored; never commit it.
{
  remoteBootMode = "uefi"; # "uefi" or "legacy"
}
