# Fallback disk device — see disk-config.nix's header comment. The real
# disk-device.nix is generated by scripts/remote-deploy.sh on every run
# and is gitignored; never commit it.
{
  remoteDiskDevice = "/dev/sda";
}
